### ISSUE TITLE
[QUESTION]: Maintainability of `attapply.py` util

### ISSUE THREAD

**Issue by umoqnier** [ElotlMX/py-elotl#22]
**Is your feature request related to a problem? Please describe.**
I was learning the code structure and I noticed that we have external code from [`foma`](https://github.com/mhulden/foma/blob/master/foma/python/attapply.py) under this path `elotl/utils/fst/attapply.py`. It seems that this is a copy-paste from the original code. I'm worried about the maintainability of this code because if any change happened in the original code we need to update our version it manually. 

My question is: **Do we need to worry about this piece of code?**. Maybe is not that important for the project to get the last updates, but what if we need to do changes to the original code?

**Describe the solution you'd like**
If we need it, we can figure out how to get the source directly from the [foma main repo](https://github.com/mhulden/foma/blob/master/foma/python/attapply.py). However, that code hasn't had any change since ~2020. Although 

**Additional context**
I think that we don't use any feature from foma, only the standalone python script `attapply.py`

Let me know what do you think about this issue and if it is necessary to take any action :)

**Comment by Lguyogiro** [comment]
I don't think there is much reason for concern here, namely because `attapply.py` is merely a utility to load an FST from the ATT format, which is a stable file format  ([https://wiki.apertium.org/wiki/ATT_format](https://wiki.apertium.org/wiki/ATT_format)) supported by multiple FST libraries. Since we don't rely on the foma library itself for any functionality beyond what is provided by the stand-alone script, it probably shouldn't be added as a dependency.

**Comment by umoqnier** [comment]
Thanks for the clarification :D I will close the issue
